### ISSUE TITLE
Null Pointer in Player Event With Paper

### ISSUE THREAD

**Issue by mysticpath93** [cjburkey01/ClaimChunk#119]
java.lang.NullPointerException: null
	at java.lang.String.replace(String.java:2143) ~[?:?]
	at com.cjburkey.claimchunk.ChunkEventHelper.handlePlayerEvent(ChunkEventHelper.java:92) ~[?:?]
	at com.cjburkey.claimchunk.ChunkEventHelper.handleBlockEvent(ChunkEventHelper.java:96) ~[?:?]
	at com.cjburkey.claimchunk.event.CancellableChunkEvents.onBlockBroken(CancellableChunkEvents.java:36) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor347.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:306) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:265) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:239) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by cjburkey01** [comment]
Someone else in the Discord server reported this when using Paper, are you using Paper too?

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/ab7e2d66877df4af9d764fd1b9060d48a462784f

**Comment by mysticpath93** [comment]
jes i have paper. are i hope soo you can fix this

**Comment by cjburkey01** [comment]
It should be good to go in 0.0.20
