### ISSUE TITLE
Claiming chunks throws internal error on 1.16.1

### ISSUE THREAD

**Issue by meowsome** [cjburkey01/ClaimChunk#148]
**Versions**
Spigot Version: 1.16.1
ClaimChunk Version: 0.0.21

**Describe the bug**
When typing /chunk claim on a 1.16.1 server, it says "An internal error occurred while attempting to perform this command", and the following happens in the console:

```
[ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'chunk' in plugin ClaimChunk v0.0.21
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:755) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$4305.000000004C0825A0.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2922.00000000F150AD90.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.UnsupportedOperationException
at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_212]
at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_212]
at com.cjburkey.claimchunk.cmd.MainHandler.claimChunk(MainHandler.java:126) ~[?:?]
at com.cjburkey.claimchunk.cmds.CmdClaim.onCall(CmdClaim.java:44) ~[?:?]
at com.cjburkey.claimchunk.cmd.CommandHandler.runCommands(CommandHandler.java:144) ~[?:?]
at com.cjburkey.claimchunk.cmd.CommandHandler.onCommand(CommandHandler.java:89) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-4d9262c-3b9cf0f]
... 20 more
```

There aren't any errors on startup and the rest of the plugin's commands appear to work fine.

**Comment by cjburkey01** [comment]
Ah dang, `Arrays.asList` returns an immutable list with your Java distribution. Do you know your Java version and operating system?

**Comment by meowsome** [comment]
I've just been testing a few different plugins with whatever comes free on https://server.pro. It says "Java 8 - Open J9" for the Java version, but I don't know about the OS.

**Comment by cjburkey01** [comment]
I’m thinking it’s Linux because I use Windows and Mac and they seem to work. I’ll put out a quick fix for that tomorrow, thanks for the report!

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/c4a4a4bdfd9d814e2a8bb8738f9c4f99071bea6c

Releasing 0.0.22 in one second!
