### ISSUE TITLE
Bone mealing into other people's chunks from the border is possible

### ISSUE THREAD

**Issue by portal-dv** [cjburkey01/ClaimChunk#198]
**Versions**
Spigot Version: Paper 1.17 
ClaimChunk Version: 0.0.23

**Describe the bug**
If you bonemeal in a chunk you claimed that's next to another ones claim, the bone meal effect will be applied to the grass blocks in the other guys chunk thats claimed too on grass

**To Reproduce**
1. Let player X claim a chunk
2. Let player Y bone meal grass blocks in an unclaimed chunk right at the border of the chunk claimed by player X

**Expected behavior**
The bone meal shouldn't affect grass in chunks claimed by other players where the player bone mealing in hasn't access to.

**Additional context**
-

**Comment by cjburkey01** [comment]
I'll add a new config option to cancel the growth in neighboring claimed chunks, which I think I can do with this event: [BlockFertilizeEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockFertilizeEvent.html#getBlocks())

**Comment by cjburkey01** [comment]
Untested solution added in commit https://github.com/cjburkey01/ClaimChunk/commit/9b545361b148a036cdd646bc8dd47a323fd11086 if you use 0.0.23, you can test the build here: https://github.com/cjburkey01/ClaimChunk/suites/3202030667/artifacts/74017668

**Comment by cjburkey01** [comment]
Feel free to reopen this if it still doesn't work 👍

**Comment by portal-dv** [comment]
Eh, yeah, now the plugin is not able to boot:

[09:20:39] [Server thread/INFO]: [ClaimChunk] Successfully enabled the ClaimChunk PlaceholderAPI expansion!
[09:20:39] [Server thread/ERROR]: Error occurred while enabling ClaimChunk v0.0.23-prev5 (Is it up to date?)
org.apache.commons.lang.SerializationException: java.lang.ClassNotFoundException: com.cjburkey.claimchunk.config.access.EntityAccess
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:166) ~[patched_1.17.1.jar:git-Paper-100]
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:193) ~[patched_1.17.1.jar:git-Paper-100]
	at org.apache.commons.lang.SerializationUtils.clone(SerializationUtils.java:81) ~[patched_1.17.1.jar:git-Paper-100]
	at com.cjburkey.claimchunk.config.access.Access.<init>(Access.java:27) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfile.<init>(ClaimChunkWorldProfile.java:108) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfileManager.getDefaultProfile(ClaimChunkWorldProfileManager.java:198) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfileManager.lambda$getProfile$1(ClaimChunkWorldProfileManager.java:85) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfileManager.getProfile(ClaimChunkWorldProfileManager.java:74) ~[?:?]
	at com.cjburkey.claimchunk.ClaimChunk.onEnable(ClaimChunk.java:256) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-100]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.cjburkey.claimchunk.config.access.EntityAccess
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:759) ~[?:?]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005) ~[?:?]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1872) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2179) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) ~[?:?]
	at java.util.HashMap.readObject(HashMap.java:1551) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1224) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) ~[?:?]
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:163) ~[patched_1.17.1.jar:git-Paper-100]
	... 19 more
[09:20:39] [Server thread/INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.23-prev5
[09:20:39] [Server thread/INFO]: [ClaimChunk] Finished disable.
