### ISSUE TITLE
After issue #198: now the plugin is not able to boot

### ISSUE THREAD

**Issue by portal-dv** [cjburkey01/ClaimChunk#201]
After updating the jar, this happens

[09:20:39] [Server thread/INFO]: [ClaimChunk] Successfully enabled the ClaimChunk PlaceholderAPI expansion!
[09:20:39] [Server thread/ERROR]: Error occurred while enabling ClaimChunk v0.0.23-prev5 (Is it up to date?)
org.apache.commons.lang.SerializationException: java.lang.ClassNotFoundException: com.cjburkey.claimchunk.config.access.EntityAccess
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:166) ~[patched_1.17.1.jar:git-Paper-100]
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:193) ~[patched_1.17.1.jar:git-Paper-100]
	at org.apache.commons.lang.SerializationUtils.clone(SerializationUtils.java:81) ~[patched_1.17.1.jar:git-Paper-100]
	at com.cjburkey.claimchunk.config.access.Access.<init>(Access.java:27) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfile.<init>(ClaimChunkWorldProfile.java:108) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfileManager.getDefaultProfile(ClaimChunkWorldProfileManager.java:198) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfileManager.lambda$getProfile$1(ClaimChunkWorldProfileManager.java:85) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at com.cjburkey.claimchunk.config.ClaimChunkWorldProfileManager.getProfile(ClaimChunkWorldProfileManager.java:74) ~[?:?]
	at com.cjburkey.claimchunk.ClaimChunk.onEnable(ClaimChunk.java:256) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-100]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.cjburkey.claimchunk.config.access.EntityAccess
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:759) ~[?:?]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005) ~[?:?]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1872) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2179) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) ~[?:?]
	at java.util.HashMap.readObject(HashMap.java:1551) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1224) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) ~[?:?]
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:163) ~[patched_1.17.1.jar:git-Paper-100]
	... 19 more
[09:20:39] [Server thread/INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.23-prev5
[09:20:39] [Server thread/INFO]: [ClaimChunk] Finished disable.

_Originally posted by @portal-dv in https://github.com/cjburkey01/ClaimChunk/issues/198#issuecomment-878927658_

**Comment by Geolykt** [comment]
The Java serialization API, the bane of every developer.

**Comment by cjburkey01** [comment]
Oop, I guess I can rip out the parts I added with that, I forget why I used it anyway.

**Comment by cjburkey01** [comment]
Ok if you want you can try this one, feel free to reopen (or open a new issue oop)

https://github.com/cjburkey01/ClaimChunk/suites/3229676474/artifacts/74851501
