### ISSUE TITLE
Error when useTitlesInsteadOfChat is true in 1.17.1 Paper

### ISSUE THREAD

**Issue by meowsome** [cjburkey01/ClaimChunk#208]
**Versions**
Spigot Version: PaperMC 1.17.1 195
ClaimChunk Version: 0.0.22

**Describe the bug**
Claiming and unclaiming chunks throws the following error when useTitlesInsteadOfChat is enabled on 1.17.1. The error does not throw when useTitlesInsteadOfChat is false. Also, I keep getting a reminder that a new version is available even though I am on the latest version.

```
[16:12:18 INFO]: Leafeons issued server command: /chunk claim
[16:12:18 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutTitle
[16:12:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[16:12:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:12:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:12:18 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:12:18 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.PacketHandler.getNMSClass(PacketHandler.java:32)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.TitleHandler.showTitle(TitleHandler.java:78)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.TitleHandler.showTitle(TitleHandler.java:31)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.Utils.toPlayer(Utils.java:58)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.MainHandler.lambda$claimChunk$3(MainHandler.java:153)
[16:12:18 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.MainHandler.lambda$claimChunk$4(MainHandler.java:153)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.service.prereq.PrereqChecker.check(PrereqChecker.java:39)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.MainHandler.claimChunk(MainHandler.java:135)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmds.CmdClaim.onCall(CmdClaim.java:44)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.CommandHandler.runCommands(CommandHandler.java:144)
[16:12:18 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.CommandHandler.onCommand(CommandHandler.java:89)
[16:12:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:12:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:12:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[16:12:18 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[16:12:18 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[16:12:18 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[16:12:18 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:12:18 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:12:18 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[16:12:18 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:12:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:12:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[16:12:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[16:12:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[16:12:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:12:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:12:32 INFO]: Leafeons issued server command: /chunk unclaim
[16:12:32 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutTitle
[16:12:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[16:12:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:12:32 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:12:32 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:12:32 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.PacketHandler.getNMSClass(PacketHandler.java:32)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.TitleHandler.showTitle(TitleHandler.java:78)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.packet.TitleHandler.showTitle(TitleHandler.java:31)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.Utils.toPlayer(Utils.java:58)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.MainHandler.unclaimChunk(MainHandler.java:231)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.MainHandler.unclaimChunk(MainHandler.java:244)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmds.CmdUnclaim.onCall(CmdUnclaim.java:44)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.CommandHandler.runCommands(CommandHandler.java:144)
[16:12:32 WARN]:        at claimchunk-0.0.22.jar//com.cjburkey.claimchunk.cmd.CommandHandler.onCommand(CommandHandler.java:89)
[16:12:32 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:12:32 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:12:32 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[16:12:32 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[16:12:32 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[16:12:32 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[16:12:32 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:12:32 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:12:32 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[16:12:32 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:12:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:12:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[16:12:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[16:12:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[16:12:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:12:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**To Reproduce**
1. Enable useTitlesInsteadOfChat
2. Type /chunk claim or /chunk unclaim

**Expected behavior**
Titles should show

**Additional context**
I haven't done much other testing in 1.17.1 other than this.

**Comment by Goldmensch** [comment]
use latest dev build https://github.com/cjburkey01/ClaimChunk/suites/3433011374/artifacts/81345956

**Comment by cjburkey01** [comment]
^^^ This problem occurs because spigot finally broke my age-old code for sending packets (title and particle support) that was meant to be cross-version.

The current development build has been patched up but I need to rewrite the utility to make use of new (within last 3 years) features.

**Comment by meowsome** [comment]
Thanks, that fixed it
