### ISSUE TITLE
Error on Initalization.

### ISSUE THREAD

**Issue by weihao** [cjburkey01/ClaimChunk#210]
smp_1         | [23:58:43 INFO]: [ClaimChunk] Enabling ClaimChunk v0.0.21
smp_1         | [23:58:43 WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
smp_1         | [23:58:43 ERROR]: [ClaimChunk] Failed to initialize data storage system "com.cjburkey.claimchunk.data.newdata.BulkMySQLDataHandler", disabling 
ClaimChunk.
smp_1         | [23:58:43 WARN]: java.lang.NumberFormatException: For input string: "YES"
smp_1         | [23:58:43 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
smp_1         | [23:58:43 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
smp_1         | [23:58:43 WARN]:        at java.base/java.lang.Double.parseDouble(Unknown Source)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.getDouble(MysqlTextValueDecoder.java:249)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:107)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:47)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:143)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:135)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1295)
smp_1         | [23:58:43 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:693)
smp_1         | [23:58:43 WARN]:        at com.cjburkey.claimchunk.data.newdata.SqlBacking.getColumnIsNullable(SqlBacking.java:68)
smp_1         | [23:58:43 WARN]:        at com.cjburkey.claimchunk.data.newdata.MySQLDataHandler.migrateAccessTable0015_0016(MySQLDataHandler.java:716)        
smp_1         | [23:58:43 WARN]:        at com.cjburkey.claimchunk.data.newdata.MySQLDataHandler.init(MySQLDataHandler.java:103)
smp_1         | [23:58:43 WARN]:        at com.cjburkey.claimchunk.data.newdata.BulkMySQLDataHandler.init(BulkMySQLDataHandler.java:58)
smp_1         | [23:58:43 WARN]:        at com.cjburkey.claimchunk.ClaimChunk.initDataHandler(ClaimChunk.java:254)
smp_1         | [23:58:43 WARN]:        at com.cjburkey.claimchunk.ClaimChunk.onEnable(ClaimChunk.java:104)
smp_1         | [23:58:43 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
smp_1         | [23:58:43 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
smp_1         | [23:58:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
smp_1         | [23:58:43 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
smp_1         | [23:58:43 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
smp_1         | [23:58:43 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
smp_1         | [23:58:43 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
smp_1         | [23:58:43 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
smp_1         | [23:58:43 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
smp_1         | [23:58:43 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
smp_1         | [23:58:43 ERROR]: [ClaimChunk] CLAIMCHUNK WILL NOT WORK WITHOUT A VALID DATA STORAGE SYSTEM!
smp_1         | [23:58:43 ERROR]: [ClaimChunk] Please double check your config and make sure it's set to the correct data information to ensure ClaimChunk can 
operate normally
smp_1         | [23:58:43 INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.21
smp_1         | [23:58:43 INFO]: [ClaimChunk] Finished disable.

**Comment by cjburkey01** [comment]
Are you able to see individual tables through your MySQL server provider? I *think* this is happening because your `information_schema.COLUMNS` table may be of a different format than expected. Was this after an upgrade or was it a fresh install?

**Comment by weihao** [comment]
i can see `access_granted` and `claimed_chunks` tables.

This is a fresh install

**Comment by cjburkey01** [comment]
Ok, what version server are you running? If it's 1.17+ I can give you a build preview that may fix it

**Comment by weihao** [comment]
`1.16.5`, i was running mysql in a persistent container when I got the error.

I just deployed a fresh copy of mysql and got the same error:
```
smp_1  | [02:07:22 INFO]: [ClaimChunk] Enabling ClaimChunk v0.0.21
smp_1  | [02:07:22 WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
smp_1  | [02:07:22 ERROR]: [ClaimChunk] Failed to initialize data storage system "com.cjburkey.claimchunk.data.newdata.BulkMySQLDataHandler", disabling ClaimChunk.
smp_1  | [02:07:22 WARN]: java.lang.NumberFormatException: For input string: "YES"
smp_1  | [02:07:22 WARN]:       at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
smp_1  | [02:07:22 WARN]:       at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
smp_1  | [02:07:22 WARN]:       at java.base/java.lang.Double.parseDouble(Unknown Source)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.protocol.a.MysqlTextValueDecoder.getDouble(MysqlTextValueDecoder.java:249)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:107)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:47)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:143)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:135)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1295)
smp_1  | [02:07:22 WARN]:       at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:693)
smp_1  | [02:07:22 WARN]:       at com.cjburkey.claimchunk.data.newdata.SqlBacking.getColumnIsNullable(SqlBacking.java:68)
smp_1  | [02:07:22 WARN]:       at com.cjburkey.claimchunk.data.newdata.MySQLDataHandler.migrateAccessTable0015_0016(MySQLDataHandler.java:716)
smp_1  | [02:07:22 WARN]:       at com.cjburkey.claimchunk.data.newdata.MySQLDataHandler.init(MySQLDataHandler.java:103)
smp_1  | [02:07:22 WARN]:       at com.cjburkey.claimchunk.data.newdata.BulkMySQLDataHandler.init(BulkMySQLDataHandler.java:58)
smp_1  | [02:07:22 WARN]:       at com.cjburkey.claimchunk.ClaimChunk.initDataHandler(ClaimChunk.java:254)
smp_1  | [02:07:22 WARN]:       at com.cjburkey.claimchunk.ClaimChunk.onEnable(ClaimChunk.java:104)
smp_1  | [02:07:22 WARN]:       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
smp_1  | [02:07:22 WARN]:       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
smp_1  | [02:07:22 WARN]:       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
smp_1  | [02:07:22 WARN]:       at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
smp_1  | [02:07:22 WARN]:       at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
smp_1  | [02:07:22 WARN]:       at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
smp_1  | [02:07:22 WARN]:       at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
smp_1  | [02:07:22 WARN]:       at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
smp_1  | [02:07:22 WARN]:       at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
smp_1  | [02:07:22 WARN]:       at java.base/java.lang.Thread.run(Unknown Source)
smp_1  | [02:07:22 ERROR]: [ClaimChunk] CLAIMCHUNK WILL NOT WORK WITHOUT A VALID DATA STORAGE SYSTEM!
smp_1  | [02:07:22 ERROR]: [ClaimChunk] Please double check your config and make sure it's set to the correct data information to ensure ClaimChunk can operate normally
smp_1  | [02:07:22 INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.21
smp_1  | [02:07:22 INFO]: [ClaimChunk] Finished disable.
```

**Comment by cjburkey01** [comment]
Ah, ok I'll pull 0.0.21 and put the fix in there, it's just a couple lines (I haven't tested it so please let me know if it is still broken). Is there a specific reason for using 0.0.21 over 0.0.22? (the version check message is annoying so maybe I need to branch 0.0.22 for compatibility and put these couple of fixes in there)

**Comment by weihao** [comment]
i am using 0.0.22. i don't think you versioned it correctly.

**Comment by cjburkey01** [comment]
Ohhhh yeah, ok here let me get a build of 0.0.22 that's fixed then

**Comment by cjburkey01** [comment]
Alright, try this one and let me know if you have any issues:
[claimchunk-0.0.22-fixed.jar.zip](https://github.com/cjburkey01/ClaimChunk/files/7077766/claimchunk-0.0.22-fixed.jar.zip)

**Comment by weihao** [comment]
```
smp_1         | [21:38:42 INFO]: [ClaimChunk] Enabling ClaimChunk v0.0.22-fixed
smp_1         | [21:38:42 WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
smp_1         | [21:38:43 ERROR]: [ClaimChunk] Failed to delete claimed chunks file
smp_1         | [21:38:43 ERROR]: [ClaimChunk] Failed to delete joined players file
smp_1         | [21:38:43 INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.22-fixed
smp_1         | [21:38:43 INFO]: [ClaimChunk] Finished disable.
```

**Comment by weihao** [comment]
resolve, dependency error

**Comment by cjburkey01** [comment]
Yes I keep seeing it and meaning to change it, here you go:
[ClaimChunk-0.0.22-fixed.zip](https://github.com/cjburkey01/ClaimChunk/files/7079835/ClaimChunk-0.0.22-fixed.zip)

**Comment by weihao** [comment]
```
smp_1         | [22:05:06 INFO]: [ClaimChunk] Enabling ClaimChunk v0.0.22-fixed
smp_1         | [22:05:06 WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
smp_1         | [22:05:06 ERROR]: [ClaimChunk] Failed to delete claimed chunks file
smp_1         | [22:05:06 ERROR]: [ClaimChunk] Failed to delete joined players file
smp_1         | [22:05:06 ERROR]: [ClaimChunk] Economy could not be setup. Make sure that you have an economy plugin (like Essentials) installed. ClaimChunk has been disabled.
smp_1         | [22:05:06 INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.22-fixed
smp_1         | [22:05:06 INFO]: [ClaimChunk] Finished disable.
```
switched from `EssentialsX` to `playerpoints` gave this error

**Comment by weihao** [comment]
> Yes I keep seeing it and meaning to change it, here you go:
> [ClaimChunk-0.0.22-fixed.zip](https://github.com/cjburkey01/ClaimChunk/files/7079835/ClaimChunk-0.0.22-fixed.zip)

is this a newly compiled jar? what does it do?

**Comment by cjburkey01** [comment]
> 
> 
> > Yes I keep seeing it and meaning to change it, here you go:
> > [ClaimChunk-0.0.22-fixed.zip](https://github.com/cjburkey01/ClaimChunk/files/7079835/ClaimChunk-0.0.22-fixed.zip)
> 
> is this a newly compiled jar? what does it do?

I just updated the driver it uses from `com.mysql.jdbc.Driver` to the newer one (which I believe I'm supposed to do, but may not make a difference for you if the warning isn't doing any harm)

**Comment by weihao** [comment]
> > > Yes I keep seeing it and meaning to change it, here you go:
> > > [ClaimChunk-0.0.22-fixed.zip](https://github.com/cjburkey01/ClaimChunk/files/7079835/ClaimChunk-0.0.22-fixed.zip)
> > 
> > 
> > is this a newly compiled jar? what does it do?
> 
> I just updated the driver it uses from `com.mysql.jdbc.Driver` to the newer one (which I believe I'm supposed to do, but may not make a difference for you if the warning isn't doing any harm or isn't there anymore in your case)

I see. Could you help investigate the error above? PlayerPoints is vault compatible, not sure why claimchunks does not support it

**Comment by cjburkey01** [comment]
There's a chance that happens because PlayerPoints could initialize after ClaimChunk, which doesn't wait at all for an economy plugin to be loaded if it isn't detected at the start. This version may be fixed, I've told ClaimChunk to wait for this specific plugin to init as a temporary band-aid that may work.
[ClaimChunk-0.0.22-fixed.zip](https://github.com/cjburkey01/ClaimChunk/files/7079957/ClaimChunk-0.0.22-fixed.zip)

**Comment by weihao** [comment]
```
smp_1         | [01:55:28 INFO]: [BungeeGuard] Enabling BungeeGuard v1.2-SNAPSHOT
smp_1         | [01:55:28 INFO]: [BungeeGuard] Using Paper's PlayerHandshakeEvent to listen for connections.
smp_1         | [01:55:28 INFO]: [PlayerPoints] Enabling PlayerPoints v3.0.3
smp_1         | [01:55:28 INFO]: [PlayerPoints] Initializing using RoseGarden v1.0.7-SNAPSHOT
smp_1         | [01:55:28 INFO]: [PlayerPoints] Data handler connected using MySQL.
smp_1         | [01:55:29 INFO]: [MysqlPlayerDataBridge] Enabling MysqlPlayerDataBridge v3.36.1
smp_1         | [01:55:29 INFO]: [MysqlPlayerDataBridge] Loading the config file...
smp_1         | [01:55:29 INFO]: [MysqlPlayerDataBridge] Vault dependency found.
smp_1         | [01:55:29 ERROR]: [MysqlPlayerDataBridge] No economy system compatible with Vault could be found!
smp_1         | [01:55:29 INFO]: [MysqlPlayerDataBridge] Compatible server version detected: 1.16.5
smp_1         | [01:55:29 INFO]: [MysqlPlayerDataBridge] Connecting to the database...
smp_1         | [01:55:29 INFO]: [MysqlPlayerDataBridge] Database connection successfull!
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Data save task is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync inventory is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync gamemode is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync armor is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync enderchest is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync experience is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync active potion effects is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync players health is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync players food is enabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync players air is disabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync players location is disabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync players bed location is disabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] Sync economy is disabled.
smp_1         | [01:55:30 INFO]: [MysqlPlayerDataBridge] MysqlPlayerDataBridge loaded successfully!
smp_1         | [01:55:30 INFO]: [WorldGuard] Enabling WorldGuard v7.0.4+f7ff984
smp_1         | [01:55:30 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] Loaded configuration for world 'world'
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
smp_1         | [01:55:30 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
smp_1         | [01:55:30 INFO]: [WorldGuard] Loading region data...
smp_1         | [01:55:30 INFO]: [CoreProtect] Enabling CoreProtect v20.1
smp_1         | [01:55:30 INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
smp_1         | [01:55:30 INFO]: [CoreProtect] Using MySQL for data storage.
smp_1         | [01:55:30 INFO]: [mcMMO] Enabling mcMMO v2.1.199
smp_1         | [01:55:30 INFO]: [mcMMO] [Debug] Loading mcMMO config.yml File...
smp_1         | [01:55:30 INFO]: [mcMMO] [Debug] No errors found in config.yml!
smp_1         | [01:55:30 INFO]: [mcMMO] Loading locale from plugins/mcMMO/locales/locale_override.properties
smp_1         | [01:55:30 INFO]: [mcMMO] [Debug] Loading mcMMO advanced.yml File...
smp_1         | [01:55:30 INFO]: [mcMMO] [Debug] No errors found in advanced.yml!
smp_1         | [01:55:30 INFO]: [mcMMO] Platform String: 1.16.5-R0.1-SNAPSHOT
smp_1         | [01:55:30 INFO]: [mcMMO] Minecraft version determined to be - 1.16.5
smp_1         | [01:55:30 INFO]: [mcMMO] Loading compatibility layers...
smp_1         | [01:55:30 INFO]: [mcMMO] Finished loading compatibility layers.
smp_1         | [01:55:30 INFO]: [mcMMO] Registering enchantments for Fishing Book...
smp_1         | [01:55:33 INFO]: [mcMMO] Killing orphans
smp_1         | [01:55:33 INFO]: [mcMMO] Enabling Acrobatics Skills
smp_1         | [01:55:33 INFO]: [mcMMO] Registered subskill: Roll
smp_1         | [01:55:33 INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
smp_1         | [01:55:33 INFO]: [ClaimChunk] Enabling ClaimChunk v0.0.22-fixed
smp_1         | [01:55:33 ERROR]: [ClaimChunk] Failed to delete claimed chunks file
smp_1         | [01:55:33 ERROR]: [ClaimChunk] Failed to delete joined players file
smp_1         | [01:55:33 ERROR]: [ClaimChunk] Economy could not be setup. Make sure that you have an economy plugin (like Essentials) installed. ClaimChunk has been disabled.
smp_1         | [01:55:33 INFO]: [ClaimChunk] Disabling ClaimChunk v0.0.22-fixed
smp_1         | [01:55:33 INFO]: [ClaimChunk] Finished disable.
smp_1         | [01:55:33 INFO]: [DiscordSRV] Enabling DiscordSRV v1.23.0
smp_1         | [01:55:34 INFO]: Starting remote control listener
smp_1         | [01:55:34 INFO]: Thread RCON Listener started
smp_1         | [01:55:34 INFO]: RCON running on 0.0.0.0:25575
smp_1         | [01:55:34 INFO]: Running delayed init tasks
smp_1         | [01:55:34 INFO]: [CoreProtect] WorldEdit logging successfully initialized.
smp_1         | [01:55:34 INFO]: [Vault] Checking for Updates ...
smp_1         | [01:55:34 INFO]: Done (13.044s)! For help, type "help"
smp_1         | [01:55:34 INFO]: Timings Reset
bungeecord_1  | [01:55:34 INFO]: [/192.168.128.1:60338] <-> InitialHandler has connected
```

**Comment by weihao** [comment]
As you may noticed, PlayerPoints is initialized, and running the latest jar, the claim chunk still gave the same error

**Comment by weihao** [comment]
I noticed `[01:55:29 ERROR]: [MysqlPlayerDataBridge] No economy system compatible with Vault could be found!` and I actually enabled the vault support in playerpoints. Now it initializes correctly.

```
smp_1         | [02:02:34 INFO]: [PlayerPoints] Enabling PlayerPoints v3.0.3
smp_1         | [02:02:34 INFO]: [PlayerPoints] Initializing using RoseGarden v1.0.7-SNAPSHOT
smp_1         | [02:02:35 INFO]: [PlayerPoints] Data handler connected using MySQL.
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Enabling MysqlPlayerDataBridge v3.36.1
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Loading the config file...
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Vault dependency found.
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Using economy system: PlayerPoints
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Compatible server version detected: 1.16.5
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Connecting to the database...
smp_1         | [02:02:35 INFO]: [MysqlPlayerDataBridge] Database connection successfull!
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Data save task is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync inventory is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync gamemode is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync armor is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync enderchest is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync experience is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync active potion effects is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync players health is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync players food is enabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync players air is disabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync players location is disabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync players bed location is disabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] Sync economy is disabled.
smp_1         | [02:02:36 INFO]: [MysqlPlayerDataBridge] MysqlPlayerDataBridge loaded successfully!
smp_1         | [02:02:36 INFO]: [WorldGuard] Enabling WorldGuard v7.0.4+f7ff984
smp_1         | [02:02:36 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] Loaded configuration for world 'world'
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
smp_1         | [02:02:36 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
smp_1         | [02:02:36 INFO]: [WorldGuard] Loading region data...
smp_1         | [02:02:36 INFO]: [CoreProtect] Enabling CoreProtect v20.1
smp_1         | [02:02:36 INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
smp_1         | [02:02:36 INFO]: [CoreProtect] Using MySQL for data storage.
smp_1         | [02:02:36 INFO]: [mcMMO] Enabling mcMMO v2.1.199
smp_1         | [02:02:36 INFO]: [mcMMO] [Debug] Loading mcMMO config.yml File...
smp_1         | [02:02:36 INFO]: [mcMMO] [Debug] No errors found in config.yml!
smp_1         | [02:02:36 INFO]: [mcMMO] Loading locale from plugins/mcMMO/locales/locale_override.properties
smp_1         | [02:02:36 INFO]: [mcMMO] [Debug] Loading mcMMO advanced.yml File...
smp_1         | [02:02:36 INFO]: [mcMMO] [Debug] No errors found in advanced.yml!
smp_1         | [02:02:36 INFO]: [mcMMO] Platform String: 1.16.5-R0.1-SNAPSHOT
smp_1         | [02:02:36 INFO]: [mcMMO] Minecraft version determined to be - 1.16.5
smp_1         | [02:02:36 INFO]: [mcMMO] Loading compatibility layers...
smp_1         | [02:02:36 INFO]: [mcMMO] Finished loading compatibility layers.
smp_1         | [02:02:36 INFO]: [mcMMO] Registering enchantments for Fishing Book...
smp_1         | [02:02:39 INFO]: [mcMMO] Killing orphans
smp_1         | [02:02:39 INFO]: [mcMMO] Enabling Acrobatics Skills
smp_1         | [02:02:39 INFO]: [mcMMO] Registered subskill: Roll
smp_1         | [02:02:39 INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
smp_1         | [02:02:39 INFO]: [ClaimChunk] Enabling ClaimChunk v0.0.22-fixed
smp_1         | [02:02:39 ERROR]: [ClaimChunk] Failed to delete claimed chunks file
smp_1         | [02:02:39 ERROR]: [ClaimChunk] Failed to delete joined players file
smp_1         | [02:02:39 INFO]: [ClaimChunk] PlaceholderAPI not found, not loading API.
smp_1         | [02:02:39 INFO]: [ClaimChunk] Initialization complete.
```

```
smp_1         | [02:02:39 ERROR]: [ClaimChunk] Failed to delete claimed chunks file
smp_1         | [02:02:39 ERROR]: [ClaimChunk] Failed to delete joined players file
```
Getting two errors, although using a database, it is trying to delete files?

**Comment by cjburkey01** [comment]
It tries to cleanup old JSON files, which it shouldn't need to do if you're using MySQL. I noticed that, the error messages themselves don't actually mean any harm but I wonder why they're being executed at all

**Comment by weihao** [comment]
yep, thanks.

closing this issue

**Comment by cjburkey01** [comment]
Awesome! 👍
