### ISSUE TITLE
Message Error

### ISSUE THREAD

**Issue by xDacksx** [cjburkey01/ClaimChunk#77]
**Versions**
Spigot Version: 1.14.4 
ClaimChunk Version: 0.0.15

**Describe the bug**
When some one enters to my chunk an error appears

[ERROR] Could not pass event PlayerInteractEvent to ClaimChunk v0.0.15

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:432) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3138.0000000018006C60.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:908) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:818) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NullPointerException

at java.lang.String.replace(String.java:4113) ~[?:1.8.0_212]

at com.cjburkey.claimchunk.ChunkEventHelper.cancelEventIfNotOwned(ChunkEventHelper.java:35) ~[?:?]

at com.cjburkey.claimchunk.ChunkEventHelper.cancelInteractionEventIfNotOwned(ChunkEventHelper.java:45) ~[?:?]

at com.cjburkey.claimchunk.event.CancellableChunkEvents.onPlayerInteract(CancellableChunkEvents.java:47) ~[?:?]

at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

... 20 more

[ERROR] Could not pass event PlayerInteractEvent to ClaimChunk v0.0.15

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:432) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3138.0000000018006C60.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:908) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:884) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:818) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NullPointerException

at java.lang.String.replace(String.java:4113) ~[?:1.8.0_212]

at com.cjburkey.claimchunk.ChunkEventHelper.cancelEventIfNotOwned(ChunkEventHelper.java:35) ~[?:?]

at com.cjburkey.claimchunk.ChunkEventHelper.cancelInteractionEventIfNotOwned(ChunkEventHelper.java:45) ~[?:?]

at com.cjburkey.claimchunk.event.CancellableChunkEvents.onPlayerInteract(CancellableChunkEvents.java:47) ~[?:?]

at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

... 20 more

[ERROR] Could not pass event PlayerInteractEvent to ClaimChunk v0.0.15

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:432) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3138.0000000018006C60.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:908) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:818) [spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NullPointerException

at java.lang.String.replace(String.java:4113) ~[?:1.8.0_212]

at com.cjburkey.claimchunk.ChunkEventHelper.cancelEventIfNotOwned(ChunkEventHelper.java:35) ~[?:?]

at com.cjburkey.claimchunk.ChunkEventHelper.cancelInteractionEventIfNotOwned(ChunkEventHelper.java:45) ~[?:?]

at com.cjburkey.claimchunk.event.CancellableChunkEvents.onPlayerInteract(CancellableChunkEvents.java:47) ~[?:?]

at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-7f33c6a]

... 20 more

**Comment by cjburkey01** [comment]
What does your `chunkNoEdit` looks like under the `messages` section of the config? That's what the error's coming from

**Comment by cjburkey01** [comment]
I'm going to close this, feel free to reopen it if it's still an issue.
